import type { Product, ProductSummary } from "./types";
import { toProductSummary } from "./types";

const platformSeller = { id: "seller-platform", name: "건강라이프 자체몰", isPlatform: true };

/** Matches the store IA nodes N-SHOP-* in docs/ia/category-tree.md §3. */
export const shopCategories = [
  { key: "supplements", label: "건강기능식품" },
  { key: "exercise", label: "운동용품" },
  { key: "sleep", label: "수면용품" },
  { key: "posture", label: "자세관리" },
  { key: "devices", label: "건강측정기기" },
  { key: "daily", label: "생활건강" },
  { key: "senior", label: "실버건강" },
  { key: "digital", label: "디지털상품" },
  { key: "subscription", label: "구독" },
  { key: "booking", label: "예약서비스" },
] as const;

/** Mock catalog for scaffolding — replaced by a real data source in TASK-008 (admin product editor). */
export const products: Product[] = [
  {
    id: "prd-001",
    slug: "omega-3-1000mg",
    saleType: "DIRECT",
    title: "오메가3 1000mg 60캡슐",
    brand: "웰니스랩",
    seller: platformSeller,
    categoryKey: "supplements",
    description: "정제어유 오메가3 1000mg, 하루 1캡슐로 충분한 EPA/DHA를 섭취할 수 있습니다.",
    images: ["/products/omega-3.svg"],
    price: 24900,
    compareAtPrice: 32000,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "오메가3 1000mg 60캡슐", metaDescription: "고순도 정제어유 오메가3" },
    relatedArticleSlugs: ["hypertension-basics"],
    adDisclosure: false,
    inventoryPolicy: { trackInventory: true, stock: 482, allowBackorder: false },
    shippingPolicy: {
      feeKrw: 0,
      freeShippingThresholdKrw: null,
      combinedShippingAllowed: true,
      estimatedDeliveryDays: "1~2일",
    },
    refundPolicy: { windowDays: 7, description: "미개봉 상품에 한해 수령 후 7일 이내 환불 가능" },
  },
  {
    id: "prd-002",
    slug: "smart-blood-pressure-monitor",
    saleType: "MARKETPLACE",
    title: "스마트 혈압계 (블루투스 연동)",
    brand: "케어텍",
    seller: { id: "seller-caretech", name: "케어텍 공식스토어", isPlatform: false },
    categoryKey: "devices",
    description: "앱과 연동해 혈압 추이를 자동으로 기록하는 가정용 혈압계입니다.",
    images: ["/products/bp-monitor.svg"],
    price: 89000,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "스마트 혈압계", metaDescription: "블루투스 연동 가정용 혈압계" },
    relatedArticleSlugs: ["hypertension-basics", "checkup-guide"],
    adDisclosure: true,
    inventoryPolicy: { trackInventory: true, stock: 37, allowBackorder: false },
    shippingPolicy: {
      feeKrw: 3000,
      freeShippingThresholdKrw: 50000,
      combinedShippingAllowed: false,
      estimatedDeliveryDays: "2~4일 (판매자 발송)",
    },
    refundPolicy: { windowDays: 14, description: "판매자 정책에 따름 — 미개봉 14일 이내" },
  },
  {
    id: "prd-003",
    slug: "sleep-sound-machine",
    saleType: "AFFILIATE",
    title: "백색소음 수면 기기",
    brand: "슬립모드",
    seller: { id: "seller-sleepmode", name: "슬립모드", isPlatform: false },
    categoryKey: "sleep",
    description: "백색소음과 자연음을 재생하는 휴대용 수면 보조 기기입니다.",
    images: ["/products/sleep-machine.svg"],
    price: 45000,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "백색소음 수면 기기", metaDescription: "휴대용 수면 보조 기기" },
    relatedArticleSlugs: ["sleep-hygiene-guide"],
    adDisclosure: true,
    externalUrl: "https://example-partner-shop.test/products/sleep-sound-machine",
    priceAsOf: "2026-07-15",
    merchantName: "파트너몰 A",
  },
  {
    id: "prd-004",
    slug: "guided-sleep-meditation-pack",
    saleType: "DIGITAL",
    title: "수면 유도 명상 오디오 12편",
    brand: "마인드케어",
    seller: platformSeller,
    categoryKey: "digital",
    description: "전문 명상 강사가 녹음한 수면 유도 오디오 12편을 다운로드하거나 스트리밍할 수 있습니다.",
    images: ["/products/meditation-pack.svg"],
    price: 12900,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "수면 유도 명상 오디오", metaDescription: "12편의 수면 명상 오디오" },
    relatedArticleSlugs: ["sleep-hygiene-guide", "stress-management"],
    adDisclosure: false,
    digitalEntitlement: { downloadLimit: 5, accessDurationDays: 365, licenseType: "PERSONAL" },
  },
  {
    id: "prd-005",
    slug: "posture-correction-band",
    saleType: "DROPSHIP",
    title: "자세교정 밴드",
    brand: "포스처핏",
    seller: platformSeller,
    categoryKey: "posture",
    description: "어깨와 등을 잡아주는 자세교정 밴드로 장시간 좌식 근무자에게 추천합니다.",
    images: ["/products/posture-band.svg"],
    price: 19800,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "자세교정 밴드", metaDescription: "좌식 근무자를 위한 자세교정 밴드" },
    relatedArticleSlugs: ["desk-stretch-routine"],
    adDisclosure: true,
    supplierName: "공급사 B",
    shippingPolicy: {
      feeKrw: 3500,
      freeShippingThresholdKrw: null,
      combinedShippingAllowed: false,
      estimatedDeliveryDays: "3~5일 (공급사 직배송)",
    },
    refundPolicy: { windowDays: 7, description: "공급사 반품 정책에 따름, 왕복 배송비 고객 부담" },
  },
  {
    id: "prd-006",
    slug: "monthly-nutrition-subscription",
    saleType: "SUBSCRIPTION",
    title: "월간 맞춤 영양제 구독",
    brand: "웰니스랩",
    seller: platformSeller,
    categoryKey: "subscription",
    description: "건강 설문 결과를 기반으로 매월 맞춤 영양제 조합을 배송해드립니다.",
    images: ["/products/subscription-box.svg"],
    price: 39000,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "월간 맞춤 영양제 구독", metaDescription: "매월 맞춤 영양제 정기배송" },
    relatedArticleSlugs: ["hypertension-basics", "desk-stretch-routine"],
    adDisclosure: false,
    subscription: { intervalDays: 30, trialDays: 0 },
    shippingPolicy: {
      feeKrw: 0,
      freeShippingThresholdKrw: null,
      combinedShippingAllowed: true,
      estimatedDeliveryDays: "매월 1일 자동 발송",
    },
  },
  {
    id: "prd-007",
    slug: "sleep-clinic-checkup",
    saleType: "BOOKING",
    title: "수면 클리닉 정밀검진 예약",
    brand: "케어파트너스",
    seller: { id: "seller-carepartners", name: "케어파트너스 클리닉", isPlatform: false },
    categoryKey: "booking",
    description: "수면다원검사를 포함한 정밀 수면 클리닉 검진을 예약합니다.",
    images: ["/products/clinic-booking.svg"],
    price: 150000,
    currency: "KRW",
    taxIncluded: true,
    status: "PUBLISHED",
    seo: { metaTitle: "수면 클리닉 정밀검진 예약", metaDescription: "수면다원검사 포함 정밀검진" },
    relatedArticleSlugs: ["sleep-hygiene-guide", "checkup-guide"],
    adDisclosure: true,
    booking: {
      availableSlots: ["2026-08-03T10:00:00+09:00", "2026-08-03T14:00:00+09:00", "2026-08-04T10:00:00+09:00"],
      durationMinutes: 90,
      cancellationPolicy: "예약일 24시간 전까지 무료 취소, 이후 취소 시 검사비의 30% 위약금",
    },
  },
];

export const productSummaries: ProductSummary[] = products.map(toProductSummary);

export function getProductsByArticleSlug(articleSlug: string): ProductSummary[] {
  return productSummaries.filter((product) => product.relatedArticleSlugs.includes(articleSlug));
}

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((product) => product.slug === slug);
}

export function getProductSummaryBySlug(slug: string): ProductSummary | undefined {
  return productSummaries.find((product) => product.slug === slug);
}
