import type { Banner, Inquiry, NewsArticle, Property, Region, Review, StatItem } from "@/types/property";

// Unsplash 무료 라이선스 사진 (출처 표기 불필요) — 매물 유형별로 재사용
const PHOTOS = {
  aptExt1: "https://images.unsplash.com/photo-1755735340764-3b077cab0c5c?auto=format&fit=crop&w=1400&q=80",
  aptExt2: "https://images.unsplash.com/photo-1757221254460-e1139728b25c?auto=format&fit=crop&w=1400&q=80",
  skylineNight1: "https://images.unsplash.com/photo-1634047412027-65df0879c98f?auto=format&fit=crop&w=1400&q=80",
  skylineNight2: "https://images.unsplash.com/photo-1611287397348-7cc69174d495?auto=format&fit=crop&w=1400&q=80",
  livingRoom: "https://images.unsplash.com/photo-1758448755856-01d3add0177b?auto=format&fit=crop&w=1400&q=80",
  oceanBalcony: "https://images.unsplash.com/photo-1523892246230-4cf65ec80cb9?auto=format&fit=crop&w=1400&q=80",
  officeGlass: "https://images.unsplash.com/photo-1757954694963-ea693d2cb1dc?auto=format&fit=crop&w=1400&q=80",
  retailCorner: "https://images.unsplash.com/photo-1646869621598-14d5f4a90ac6?auto=format&fit=crop&w=1400&q=80",
  house1: "https://images.unsplash.com/photo-1760067537293-6b30141d6a52?auto=format&fit=crop&w=1400&q=80",
  houseNight: "https://images.unsplash.com/photo-1564347208312-4edb9f9a866f?auto=format&fit=crop&w=1400&q=80",
} as const;

export const properties: Property[] = [
  {
    id: "gangnam-tower-101",
    title: "강남 프리미엄 타워 101동",
    dealType: "매매",
    propertyType: "아파트",
    listingType: "일반",
    price: "22억 5,000",
    priceValue: 225000,
    city: "서울",
    district: "강남구",
    areaM2: 114,
    floor: "24/35층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["PREMIUM", "HOT"],
    gradient: "from-slate-900 via-blue-900 to-slate-800",
    address: "서울특별시 강남구 테헤란로 427",
    propertyNumber: "A-2026-0142",
    maintenanceFee: "32만원/월",
    direction: "남향",
    builtYear: 2019,
    moveInDate: "즉시입주",
    images: [PHOTOS.skylineNight1, PHOTOS.skylineNight2, PHOTOS.livingRoom, PHOTOS.aptExt1],
    description: {
      features: [
        "강남역 도보 7분, 2호선·신분당선 더블 역세권",
        "3면 개방형 판상형 구조로 채광 우수",
        "단지 내 피트니스·조식서비스 운영",
      ],
      pros: ["초등학교 도보 5분", "대형 커뮤니티 시설", "24시간 보안 컨시어지"],
      cautions: ["일부 세대 전세 재계약 진행 중", "주차 2대 이상은 관리사무소 협의 필요"],
      renovated: true,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "강남역 2호선", distanceM: 550 },
      { category: "학교", name: "역삼초등학교", distanceM: 420 },
      { category: "마트", name: "코스트코 양재점", distanceM: 1800 },
      { category: "병원", name: "강남세브란스병원", distanceM: 1200 },
    ],
  },
  {
    id: "seocho-hill-view",
    title: "서초 힐뷰 오피스텔",
    dealType: "전세",
    propertyType: "오피스텔",
    listingType: "일반",
    price: "6억 3,000",
    priceValue: 63000,
    city: "서울",
    district: "서초구",
    areaM2: 59,
    floor: "12/20층",
    bedroomCount: 1,
    bathroomCount: 1,
    badges: ["NEW"],
    gradient: "from-blue-900 via-sky-800 to-slate-900",
    address: "서울특별시 서초구 서초대로 302",
    propertyNumber: "A-2026-0198",
    maintenanceFee: "18만원/월",
    direction: "동남향",
    builtYear: 2022,
    moveInDate: "2026-03 입주 가능",
    images: [PHOTOS.aptExt2, PHOTOS.livingRoom, PHOTOS.skylineNight2],
    description: {
      features: ["신축 오피스텔로 준공 3년 이내", "고층부 서리풀공원 조망"],
      pros: ["반려동물 동반 가능", "필로티 주차로 우천 시 편리"],
      cautions: ["일부 저층 세대는 조망 제한"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "반려동물", "에어컨", "CCTV"],
    nearby: [
      { category: "지하철", name: "서초역 2호선", distanceM: 380 },
      { category: "공원", name: "서리풀공원", distanceM: 300 },
      { category: "편의점", name: "GS25 서초점", distanceM: 90 },
    ],
  },
  {
    id: "haeundae-marine-view",
    title: "해운대 마린뷰 레지던스",
    dealType: "매매",
    propertyType: "아파트",
    listingType: "일반",
    price: "14억 8,000",
    priceValue: 148000,
    city: "부산",
    district: "해운대구",
    areaM2: 101,
    floor: "31/42층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["PREMIUM"],
    gradient: "from-sky-900 via-cyan-800 to-slate-900",
    address: "부산광역시 해운대구 마린시티2로 33",
    propertyNumber: "A-2026-0221",
    maintenanceFee: "45만원/월",
    direction: "남동향",
    builtYear: 2016,
    moveInDate: "2026-05 입주 가능",
    images: [PHOTOS.oceanBalcony, PHOTOS.skylineNight1, PHOTOS.livingRoom],
    description: {
      features: ["전 세대 오션뷰", "마린시티 랜드마크 단지"],
      pros: ["해변 도보 10분", "요트경기장 인접"],
      cautions: ["성수기 관광객으로 주변 소음 있을 수 있음"],
      renovated: true,
    },
    options: ["주차", "엘리베이터", "에어컨", "발코니", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "센텀시티역 2호선", distanceM: 1500 },
      { category: "마트", name: "신세계센텀시티", distanceM: 1700 },
      { category: "학교", name: "해강초등학교", distanceM: 650 },
    ],
  },
  {
    id: "seongsu-loft-201",
    title: "성수 디자이너 로프트",
    dealType: "월세",
    propertyType: "오피스텔",
    listingType: "일반",
    price: "3,000",
    priceValue: 3000,
    monthlyRent: "월 220",
    monthlyRentValue: 220,
    city: "서울",
    district: "성동구",
    areaM2: 42,
    floor: "5/8층",
    bedroomCount: 1,
    bathroomCount: 1,
    badges: ["HOT"],
    gradient: "from-slate-800 via-indigo-900 to-slate-900",
    address: "서울특별시 성동구 성수이로 77",
    propertyNumber: "A-2026-0305",
    maintenanceFee: "12만원/월",
    direction: "서향",
    builtYear: 2021,
    moveInDate: "즉시입주",
    images: [PHOTOS.livingRoom, PHOTOS.aptExt2],
    description: {
      features: ["복층 로프트 구조", "성수동 카페거리 도보 3분"],
      pros: ["감성 인테리어", "반려동물 가능"],
      cautions: ["엘리베이터 없는 저층 건물"],
      renovated: false,
    },
    options: ["반려동물", "에어컨", "붙박이장", "발코니"],
    nearby: [
      { category: "지하철", name: "성수역 2호선", distanceM: 480 },
      { category: "편의점", name: "CU 성수점", distanceM: 120 },
      { category: "버스", name: "성수사거리 정류장", distanceM: 200 },
    ],
  },
  {
    id: "pangyo-tech-office",
    title: "판교 테크노밸리 사무실",
    dealType: "매매",
    propertyType: "사무실",
    listingType: "일반",
    price: "18억",
    priceValue: 180000,
    city: "경기",
    district: "성남시 분당구",
    areaM2: 165,
    floor: "9/15층",
    bedroomCount: 0,
    bathroomCount: 1,
    badges: [],
    gradient: "from-blue-950 via-slate-900 to-slate-800",
    address: "경기도 성남시 분당구 판교역로 235",
    propertyNumber: "A-2026-0410",
    maintenanceFee: "58만원/월",
    direction: "남향",
    builtYear: 2018,
    moveInDate: "협의 가능",
    images: [PHOTOS.officeGlass, PHOTOS.skylineNight2],
    description: {
      features: ["판교역 도보 5분 프라임 오피스", "IT 기업 밀집 지역"],
      pros: ["대형 회의실 임대 가능", "지하 연결 주차장"],
      cautions: ["출퇴근 시간 주차장 혼잡"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "판교역 신분당선", distanceM: 400 },
      { category: "마트", name: "현대백화점 판교점", distanceM: 900 },
    ],
  },
  {
    id: "yeouido-riverfront",
    title: "여의도 리버프론트 오피스텔",
    dealType: "전세",
    propertyType: "오피스텔",
    listingType: "일반",
    price: "8억 1,000",
    priceValue: 81000,
    city: "서울",
    district: "영등포구",
    areaM2: 76,
    floor: "18/25층",
    bedroomCount: 2,
    bathroomCount: 1,
    badges: ["NEW", "PREMIUM"],
    gradient: "from-indigo-950 via-blue-900 to-sky-900",
    address: "서울특별시 영등포구 여의대로 66",
    propertyNumber: "A-2026-0488",
    maintenanceFee: "27만원/월",
    direction: "북서향",
    builtYear: 2023,
    moveInDate: "2026-04 입주 가능",
    images: [PHOTOS.aptExt1, PHOTOS.livingRoom, PHOTOS.skylineNight1],
    description: {
      features: ["한강 조망 세대", "여의도 업무지구 도보권"],
      pros: ["신축 커뮤니티 라운지", "지하철 2개 노선 이용 가능"],
      cautions: ["일부 세대 야간 조명 반사"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "여의도역 5·9호선", distanceM: 600 },
      { category: "공원", name: "여의도한강공원", distanceM: 350 },
      { category: "병원", name: "성모병원 여의도", distanceM: 900 },
    ],
  },
  {
    id: "jamsil-riverpark",
    title: "잠실 리버파크 아파트",
    dealType: "매매",
    propertyType: "아파트",
    listingType: "일반",
    price: "19억 2,000",
    priceValue: 192000,
    city: "서울",
    district: "송파구",
    areaM2: 109,
    floor: "15/25층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["HOT"],
    gradient: "from-indigo-900 via-blue-900 to-slate-900",
    address: "서울특별시 송파구 올림픽로 265",
    propertyNumber: "A-2026-0522",
    maintenanceFee: "38만원/월",
    direction: "남향",
    builtYear: 2015,
    moveInDate: "2026-06 입주 가능",
    images: [PHOTOS.aptExt2, PHOTOS.skylineNight1, PHOTOS.livingRoom],
    description: {
      features: ["한강·롯데타워 조망", "잠실 학군 인접"],
      pros: ["대단지 커뮤니티", "석촌호수 도보 10분"],
      cautions: ["재건축 이슈로 시세 변동성 있음"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장", "CCTV"],
    nearby: [
      { category: "지하철", name: "잠실나루역 2호선", distanceM: 700 },
      { category: "학교", name: "잠일초등학교", distanceM: 350 },
      { category: "공원", name: "석촌호수공원", distanceM: 900 },
    ],
  },
  {
    id: "gwanggyo-lakeview",
    title: "광교 레이크뷰 아파트",
    dealType: "전세",
    propertyType: "아파트",
    listingType: "일반",
    price: "7억",
    priceValue: 70000,
    city: "경기",
    district: "수원시 영통구",
    areaM2: 84,
    floor: "20/28층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["NEW"],
    gradient: "from-sky-900 via-blue-900 to-slate-900",
    address: "경기도 수원시 영통구 광교호수로 156",
    propertyNumber: "A-2026-0567",
    maintenanceFee: "24만원/월",
    direction: "남서향",
    builtYear: 2021,
    moveInDate: "즉시입주",
    images: [PHOTOS.aptExt1, PHOTOS.livingRoom],
    description: {
      features: ["광교호수공원 조망", "신분당선 역세권"],
      pros: ["대형 상업시설 인접", "학원가 도보권"],
      cautions: ["출퇴근 시간 진입로 정체"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "반려동물", "에어컨", "발코니"],
    nearby: [
      { category: "지하철", name: "광교역 신분당선", distanceM: 900 },
      { category: "공원", name: "광교호수공원", distanceM: 250 },
      { category: "마트", name: "롯데아울렛 광교점", distanceM: 700 },
    ],
  },
  {
    id: "itaewon-sensibility-house",
    title: "이태원 감성 주택",
    dealType: "월세",
    propertyType: "주택",
    listingType: "일반",
    price: "5,000",
    priceValue: 5000,
    monthlyRent: "월 180",
    monthlyRentValue: 180,
    city: "서울",
    district: "용산구",
    areaM2: 66,
    floor: "2/3층",
    bedroomCount: 2,
    bathroomCount: 1,
    badges: [],
    gradient: "from-slate-800 via-red-900 to-slate-900",
    address: "서울특별시 용산구 이태원로 145",
    propertyNumber: "A-2026-0603",
    maintenanceFee: "8만원/월",
    direction: "남향",
    builtYear: 2010,
    moveInDate: "2026-04 입주 가능",
    images: [PHOTOS.house1, PHOTOS.livingRoom],
    description: {
      features: ["복층 테라스 주택", "외국인 상권 인접"],
      pros: ["개성 있는 인테리어", "루프탑 테라스 보유"],
      cautions: ["주차 공간 협소"],
      renovated: true,
    },
    options: ["반려동물", "에어컨", "발코니"],
    nearby: [
      { category: "지하철", name: "이태원역 6호선", distanceM: 450 },
      { category: "편의점", name: "이마트24 이태원점", distanceM: 150 },
    ],
  },
  {
    id: "songdo-central-park",
    title: "송도 센트럴파크 오피스텔",
    dealType: "매매",
    propertyType: "오피스텔",
    listingType: "분양",
    price: "9억 5,000",
    priceValue: 95000,
    city: "인천",
    district: "연수구",
    areaM2: 72,
    floor: "22/30층",
    bedroomCount: 2,
    bathroomCount: 1,
    badges: ["PREMIUM", "NEW"],
    gradient: "from-blue-950 via-sky-900 to-slate-900",
    address: "인천광역시 연수구 컨벤시아대로 165",
    propertyNumber: "A-2026-0644",
    maintenanceFee: "22만원/월",
    direction: "동향",
    builtYear: 2020,
    moveInDate: "협의 가능",
    images: [PHOTOS.aptExt1, PHOTOS.skylineNight2, PHOTOS.livingRoom],
    description: {
      features: ["센트럴파크 조망", "국제업무단지 인접"],
      pros: ["외국계 기업 밀집 지역", "수변공원 산책로"],
      cautions: ["차량 없이는 대중교통 다소 불편"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "센트럴파크역 인천1호선", distanceM: 550 },
      { category: "공원", name: "송도센트럴파크", distanceM: 200 },
    ],
  },
  {
    id: "gangnam-station-retail",
    title: "강남 역세권 상가 (급매)",
    dealType: "매매",
    propertyType: "상가",
    listingType: "급매",
    price: "32억",
    priceValue: 320000,
    city: "서울",
    district: "강남구",
    areaM2: 145,
    floor: "1/8층",
    bedroomCount: 0,
    bathroomCount: 1,
    badges: ["PREMIUM"],
    gradient: "from-slate-900 via-amber-900 to-slate-800",
    address: "서울특별시 강남구 강남대로 396",
    propertyNumber: "A-2026-0689",
    maintenanceFee: "70만원/월",
    direction: "정남향",
    builtYear: 2012,
    moveInDate: "즉시입주",
    images: [PHOTOS.retailCorner, PHOTOS.skylineNight2],
    description: {
      features: ["강남역 1번 출구 도보 3분 코너 상가", "유동인구 최상위 입지"],
      pros: ["1층 전면 3면 노출", "장기 임차인 계약 중"],
      cautions: ["권리금 별도 협의 필요"],
      renovated: false,
    },
    options: ["엘리베이터", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "강남역 2호선", distanceM: 200 },
      { category: "버스", name: "강남역 버스환승센터", distanceM: 150 },
    ],
  },
  {
    id: "bundang-garden-house",
    title: "분당 전원주택 (경매)",
    dealType: "매매",
    propertyType: "주택",
    listingType: "경매",
    price: "15억",
    priceValue: 150000,
    city: "경기",
    district: "성남시 분당구",
    areaM2: 198,
    floor: "지상 2층",
    bedroomCount: 4,
    bathroomCount: 3,
    badges: [],
    gradient: "from-emerald-900 via-slate-900 to-slate-800",
    address: "경기도 성남시 분당구 운중로 88",
    propertyNumber: "A-2026-0715",
    maintenanceFee: "15만원/월",
    direction: "남향",
    builtYear: 2014,
    moveInDate: "협의 가능",
    images: [PHOTOS.houseNight, PHOTOS.house1],
    description: {
      features: ["넓은 정원과 개인 마당", "판교 테크노밸리 차량 10분"],
      pros: ["프라이빗한 주거 환경", "반려동물 자유롭게 양육 가능"],
      cautions: ["대중교통 이용 시 마을버스 환승 필요"],
      renovated: true,
    },
    options: ["주차", "반려동물", "에어컨", "발코니", "CCTV"],
    nearby: [
      { category: "학교", name: "운중초등학교", distanceM: 500 },
      { category: "마트", name: "판교 이마트", distanceM: 2400 },
    ],
  },
];

export const featuredProperties: Property[] = properties.slice(0, 6);

export const popularRegions: Region[] = [
  { id: "gangnam", name: "강남구", city: "서울", listingCount: 1284, avgPricePerPyeong: "8,420만원", gradient: "from-blue-900 to-slate-900" },
  { id: "seocho", name: "서초구", city: "서울", listingCount: 942, avgPricePerPyeong: "7,650만원", gradient: "from-slate-900 to-indigo-900" },
  { id: "haeundae", name: "해운대구", city: "부산", listingCount: 611, avgPricePerPyeong: "3,120만원", gradient: "from-sky-900 to-blue-950" },
  { id: "seongsu", name: "성수동", city: "서울", listingCount: 388, avgPricePerPyeong: "6,890만원", gradient: "from-indigo-900 to-slate-800" },
  { id: "pangyo", name: "판교", city: "경기", listingCount: 705, avgPricePerPyeong: "4,530만원", gradient: "from-slate-800 to-blue-900" },
  { id: "songdo", name: "송도", city: "인천", listingCount: 456, avgPricePerPyeong: "2,470만원", gradient: "from-blue-950 to-sky-900" },
  { id: "itaewon", name: "이태원", city: "서울", listingCount: 302, avgPricePerPyeong: "5,240만원", gradient: "from-slate-900 to-blue-950" },
  { id: "jamsil", name: "잠실", city: "서울", listingCount: 819, avgPricePerPyeong: "6,180만원", gradient: "from-indigo-950 to-slate-900" },
  { id: "yeouido", name: "여의도", city: "서울", listingCount: 534, avgPricePerPyeong: "6,940만원", gradient: "from-blue-900 to-indigo-950" },
  { id: "gwanggyo", name: "광교", city: "경기", listingCount: 271, avgPricePerPyeong: "3,280만원", gradient: "from-sky-950 to-slate-900" },
];

export const reviews: Review[] = [
  {
    id: "r1",
    author: "김O훈",
    role: "매수 고객",
    content: "검색 필터가 정교해서 원하는 조건의 매물을 30분 만에 찾았습니다. 상담도 빨랐어요.",
    rating: 5,
  },
  {
    id: "r2",
    author: "이O영",
    role: "임차인",
    content: "지역별 시세 비교가 한눈에 보여서 결정이 쉬웠습니다. 상세 페이지 정보가 정말 꼼꼼해요.",
    rating: 5,
  },
  {
    id: "r3",
    author: "박O민",
    role: "투자자",
    content: "AI 추천 매물이 실제로 관심사와 잘 맞아서 놀랐습니다. 인기 지역 데이터도 유용했어요.",
    rating: 4,
  },
  {
    id: "r4",
    author: "최O진",
    role: "임대인",
    content: "매물 등록부터 문의 관리까지 프로세스가 깔끔합니다. 담당 중개사님과 소통도 원활했어요.",
    rating: 5,
  },
];

export const staffMembers = ["김민준", "이서연", "박도윤", "최지호"];

export const inquiries: Inquiry[] = [
  {
    id: "inq-1001",
    name: "정하윤",
    phone: "010-1234-5678",
    message: "강남 프리미엄 타워 101동 방문 상담을 신청하고 싶습니다. 이번 주 토요일 오후 가능할까요?",
    propertyTitle: "강남 프리미엄 타워 101동",
    status: "진행",
    assignee: "김민준",
    memo: "토요일 14시 방문 예약 확정, 주차 안내 필요",
    createdAt: "2026-07-20T09:12:00.000Z",
  },
  {
    id: "inq-1002",
    name: "오세훈",
    phone: "010-2345-6789",
    message: "해운대 마린뷰 레지던스 오션뷰 세대 잔여 여부 문의드립니다.",
    propertyTitle: "해운대 마린뷰 레지던스",
    status: "접수",
    assignee: "",
    memo: "",
    createdAt: "2026-07-21T02:40:00.000Z",
  },
  {
    id: "inq-1003",
    name: "강수빈",
    phone: "010-3456-7890",
    message: "판교 테크노밸리 사무실 임대 조건도 가능한지 궁금합니다.",
    propertyTitle: "판교 테크노밸리 사무실",
    status: "완료",
    assignee: "이서연",
    memo: "임대 불가, 매매만 진행 안내 완료",
    createdAt: "2026-07-18T05:05:00.000Z",
  },
  {
    id: "inq-1004",
    name: "문지훈",
    phone: "010-4567-8901",
    message: "분당 전원주택 경매 절차와 명도 관련해서 상담받고 싶어요.",
    propertyTitle: "분당 전원주택 (경매)",
    status: "접수",
    assignee: "박도윤",
    memo: "",
    createdAt: "2026-07-22T11:30:00.000Z",
  },
  {
    id: "inq-1005",
    name: "한소율",
    phone: "010-5678-9012",
    message: "타 지역 이사 예정인데, 전반적으로 서울 전세 매물 추천받을 수 있을까요?",
    status: "취소",
    assignee: "",
    memo: "고객 요청으로 상담 취소",
    createdAt: "2026-07-15T07:20:00.000Z",
  },
];

export const banners: Banner[] = [
  {
    id: "ban-1",
    title: "프리미엄 신규 입주 매물 특별전",
    subtitle: "송도·판교 신축 오피스텔 분양 매물 모음",
    href: "/search?type=new-sale",
    active: true,
    gradient: "from-blue-900 via-sky-800 to-slate-900",
  },
  {
    id: "ban-2",
    title: "급매 특가 매물전",
    subtitle: "시세보다 낮은 급매 매물을 지금 확인하세요",
    href: "/search?type=urgent",
    active: true,
    gradient: "from-slate-900 via-amber-900 to-slate-800",
  },
  {
    id: "ban-3",
    title: "AI 맞춤 추천 서비스 오픈",
    subtitle: "관심 조건만 입력하면 AI가 매물을 추천해드려요",
    href: "/",
    active: false,
    gradient: "from-indigo-900 via-blue-900 to-slate-900",
  },
];

export const stats: StatItem[] = [
  { id: "listings", label: "등록 매물", value: 48210, suffix: "+" },
  { id: "deals", label: "거래 완료", value: 12480, suffix: "+" },
  { id: "visitors", label: "월간 방문자", value: 963000, suffix: "+" },
  { id: "reviews", label: "고객 리뷰", value: 8340, suffix: "+" },
];

export const visitorTrend: { date: string; visitors: number }[] = [
  { date: "07-10", visitors: 2840 },
  { date: "07-11", visitors: 3120 },
  { date: "07-12", visitors: 2960 },
  { date: "07-13", visitors: 3380 },
  { date: "07-14", visitors: 3510 },
  { date: "07-15", visitors: 3200 },
  { date: "07-16", visitors: 3050 },
  { date: "07-17", visitors: 3430 },
  { date: "07-18", visitors: 3690 },
  { date: "07-19", visitors: 3880 },
  { date: "07-20", visitors: 3540 },
  { date: "07-21", visitors: 3390 },
  { date: "07-22", visitors: 3720 },
  { date: "07-23", visitors: 3842 },
];

export const topSearchedKeywords: { keyword: string; count: number }[] = [
  { keyword: "강남 10억 이하 아파트", count: 1284 },
  { keyword: "신축 오피스텔", count: 962 },
  { keyword: "역세권 전세", count: 845 },
  { keyword: "해운대 마린뷰", count: 611 },
  { keyword: "반려동물 가능 주택", count: 438 },
];

export const topViewedProperties: { title: string; views: number }[] = [
  { title: "강남 프리미엄 타워 101동", views: 4820 },
  { title: "해운대 마린뷰 레지던스", views: 3910 },
  { title: "여의도 리버프론트 오피스텔", views: 3340 },
  { title: "잠실 리버파크 아파트", views: 2870 },
  { title: "송도 센트럴파크 오피스텔", views: 2210 },
];

export const newsArticles: NewsArticle[] = [
  {
    id: "market-trend-2026-q1",
    title: "2026년 1분기 수도권 아파트 거래량, 전분기 대비 완만한 회복세",
    excerpt: "역세권 신축 단지를 중심으로 거래가 늘며 매매 심리가 점차 살아나는 모습입니다.",
    content: [
      "2026년 1분기 수도권 아파트 거래량이 전분기 대비 완만한 회복세를 보이고 있습니다. 특히 역세권 신축 단지를 중심으로 거래가 늘며 매매 심리가 점차 살아나는 모습입니다.",
      "부동산 업계 관계자들은 금리 안정과 함께 실수요자들의 매수 심리가 회복되고 있다고 분석합니다. 다만 지역별 편차는 여전히 크게 나타나고 있어, 서울 강남권과 주요 업무지구 인접 단지에 거래가 집중되는 양상입니다.",
      "전문가들은 2분기에도 이 같은 흐름이 이어질 것으로 전망하면서도, 공급 물량 추이와 정책 변화에 따라 시장 분위기가 달라질 수 있다고 조언했습니다.",
    ],
    category: "시장동향",
    publishedAt: "2026-01-14",
  },
  {
    id: "policy-update-jeonse",
    title: "전세보증금 반환보증 가입 요건 완화, 임차인 부담 줄어드나",
    excerpt: "정부가 발표한 개정안의 주요 내용과 세입자가 챙겨야 할 체크리스트를 정리했습니다.",
    content: [
      "정부가 전세보증금 반환보증 가입 요건을 완화하는 개정안을 발표했습니다. 이번 개정으로 그동안 보증 가입이 어려웠던 일부 주택 유형의 임차인들도 보증금 보호를 받을 수 있게 됐습니다.",
      "주요 개정 내용으로는 보증한도 상향, 심사 서류 간소화, 온라인 신청 절차 확대 등이 포함됩니다. 국토교통부는 이를 통해 임차인의 보증금 미반환 위험이 크게 줄어들 것으로 기대한다고 밝혔습니다.",
      "세입자는 계약 전 반환보증 가입 가능 여부를 미리 확인하고, 등기부등본상 권리관계와 선순위 채권을 꼼꼼히 점검하는 것이 중요합니다.",
    ],
    category: "정책",
    publishedAt: "2026-02-03",
  },
  {
    id: "region-report-gwanggyo",
    title: "광교신도시, 호수공원 프리미엄에 힘입어 실수요 꾸준",
    excerpt: "신분당선 접근성과 대형 상업시설이 어우러지며 학군 수요까지 겹치는 추세입니다.",
    content: [
      "광교신도시가 호수공원 프리미엄과 신분당선 접근성에 힘입어 꾸준한 실수요를 이어가고 있습니다. 대형 상업시설과 우수 학군이 어우러지면서 실거주 목적의 매수 문의가 늘고 있는 것으로 나타났습니다.",
      "특히 광교호수공원 인접 단지는 조망과 산책 환경을 중시하는 30~40대 수요자들에게 꾸준한 인기를 얻고 있으며, 인근 학원가 확충도 학령기 자녀를 둔 가구의 관심을 끄는 요인으로 꼽힙니다.",
      "지역 공인중개사들은 신분당선 추가 연장 계획과 함께 중장기적으로도 실수요 기반의 안정적인 흐름이 이어질 것으로 내다봤습니다.",
    ],
    category: "지역리포트",
    publishedAt: "2026-02-18",
  },
  {
    id: "interview-agent-tips",
    title: "[인터뷰] 20년차 공인중개사가 말하는 상가 매물 보는 법",
    excerpt: "권리금, 유동인구, 계약 조건까지 — 상가 투자 전 반드시 확인해야 할 포인트.",
    content: [
      "20년차 베테랑 공인중개사와의 인터뷰를 통해 상가 매물을 볼 때 반드시 확인해야 할 포인트를 정리했습니다.",
      "\"권리금은 반드시 시설·영업·바닥 권리금으로 구분해서 협의해야 합니다. 특히 바닥 권리금은 법적 보호를 받기 어려운 경우가 많아 신중한 접근이 필요합니다\"라고 강조했습니다.",
      "유동인구 조사는 시간대별·요일별로 최소 일주일 이상 직접 관찰하는 것을 추천했으며, 장기 임차인이 있는 경우 계약 갱신 조건과 잔여 기간을 명확히 확인해야 한다고 조언했습니다.",
    ],
    category: "인터뷰",
    publishedAt: "2026-03-02",
  },
];

export const searchKeywords = [
  "강남 10억 이하 아파트",
  "주차 가능한 상가",
  "신축 오피스텔",
  "해운대 마린뷰",
  "판교 사무실 매매",
  "역세권 전세",
  "반려동물 가능 주택",
  "즉시입주 아파트",
];
