import type { Banner, Inquiry, NewsArticle, Property, Region, Review, StatItem } from "@/types/property";

// Unsplash 무료 라이선스 사진 (출처 표기 불필요) — 매물 유형별로 재사용
const PHOTOS = {
  aptExt1: "https://images.unsplash.com/photo-1755735340764-3b077cab0c5c?auto=format&fit=crop&w=1400&q=80",
  aptExt2: "https://images.unsplash.com/photo-1757221254460-e1139728b25c?auto=format&fit=crop&w=1400&q=80",
  skylineNight1: "https://images.unsplash.com/photo-1634047412027-65df0879c98f?auto=format&fit=crop&w=1400&q=80",
  skylineNight2: "https://images.unsplash.com/photo-1611287397348-7cc69174d495?auto=format&fit=crop&w=1400&q=80",
  livingRoom: "https://images.unsplash.com/photo-1758448755856-01d3add0177b?auto=format&fit=crop&w=1400&q=80",
  officeGlass: "https://images.unsplash.com/photo-1757954694963-ea693d2cb1dc?auto=format&fit=crop&w=1400&q=80",
  retailCorner: "https://images.unsplash.com/photo-1646869621598-14d5f4a90ac6?auto=format&fit=crop&w=1400&q=80",
  house1: "https://images.unsplash.com/photo-1760067537293-6b30141d6a52?auto=format&fit=crop&w=1400&q=80",
  houseNight: "https://images.unsplash.com/photo-1564347208312-4edb9f9a866f?auto=format&fit=crop&w=1400&q=80",
} as const;

// 대구광역시 8개 구·군 매물로 구성 (서비스 주력 상권)
export const properties: Property[] = [
  {
    id: "suseong-beomeo-tower",
    title: "수성구 범어 센트럴 아파트",
    dealType: "매매",
    propertyType: "아파트",
    listingType: "일반",
    price: "12억 5,000",
    priceValue: 125000,
    city: "대구",
    district: "수성구",
    areaM2: 114,
    floor: "24/35층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["PREMIUM", "HOT"],
    gradient: "from-slate-900 via-blue-900 to-slate-800",
    address: "대구광역시 수성구 범어동 달구벌대로 2435",
    propertyNumber: "D-2026-0142",
    maintenanceFee: "28만원/월",
    direction: "남향",
    builtYear: 2019,
    moveInDate: "즉시입주",
    images: [PHOTOS.skylineNight1, PHOTOS.skylineNight2, PHOTOS.livingRoom, PHOTOS.aptExt1],
    description: {
      features: [
        "범어역 2호선 도보 5분, 수성구청·법원 인접",
        "3면 개방형 판상형 구조로 채광 우수",
        "단지 내 피트니스·조식서비스 운영",
      ],
      pros: ["범어초·경신고 학군 도보권", "대형 커뮤니티 시설", "24시간 보안 컨시어지"],
      cautions: ["일부 세대 전세 재계약 진행 중", "주차 2대 이상은 관리사무소 협의 필요"],
      renovated: true,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "범어역 2호선", distanceM: 420 },
      { category: "학교", name: "범어초등학교", distanceM: 380 },
      { category: "마트", name: "롯데백화점 대구점", distanceM: 1500 },
      { category: "병원", name: "영남대학교병원", distanceM: 1800 },
    ],
  },
  {
    id: "suseong-manchon-officetel",
    title: "수성구 만촌 리버뷰 오피스텔",
    dealType: "전세",
    propertyType: "오피스텔",
    listingType: "일반",
    price: "3억 2,000",
    priceValue: 32000,
    city: "대구",
    district: "수성구",
    areaM2: 59,
    floor: "12/18층",
    bedroomCount: 1,
    bathroomCount: 1,
    badges: ["NEW"],
    gradient: "from-blue-900 via-sky-800 to-slate-900",
    address: "대구광역시 수성구 만촌동 청수로 88",
    propertyNumber: "D-2026-0198",
    maintenanceFee: "14만원/월",
    direction: "동남향",
    builtYear: 2022,
    moveInDate: "2026-03 입주 가능",
    images: [PHOTOS.aptExt2, PHOTOS.livingRoom, PHOTOS.skylineNight2],
    description: {
      features: ["신축 오피스텔로 준공 3년 이내", "고층부 신천 조망"],
      pros: ["반려동물 동반 가능", "만촌역 도보 8분"],
      cautions: ["일부 저층 세대는 조망 제한"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "반려동물", "에어컨", "CCTV"],
    nearby: [
      { category: "지하철", name: "만촌역 2호선", distanceM: 640 },
      { category: "공원", name: "신천둔치", distanceM: 300 },
      { category: "편의점", name: "GS25 만촌점", distanceM: 90 },
    ],
  },
  {
    id: "jung-dongseongno-retail",
    title: "중구 동성로 코너 상가 (급매)",
    dealType: "매매",
    propertyType: "상가",
    listingType: "급매",
    price: "18억",
    priceValue: 180000,
    city: "대구",
    district: "중구",
    areaM2: 145,
    floor: "1/6층",
    bedroomCount: 0,
    bathroomCount: 1,
    badges: ["PREMIUM"],
    gradient: "from-slate-900 via-amber-900 to-slate-800",
    address: "대구광역시 중구 동성로2가 junction 25",
    propertyNumber: "D-2026-0233",
    maintenanceFee: "55만원/월",
    direction: "정남향",
    builtYear: 2011,
    moveInDate: "즉시입주",
    images: [PHOTOS.retailCorner, PHOTOS.skylineNight2],
    description: {
      features: ["동성로 중앙로역 1번 출구 도보 3분 코너 상가", "대구 최대 유동인구 상권"],
      pros: ["1층 전면 3면 노출", "장기 임차인 계약 중"],
      cautions: ["권리금 별도 협의 필요"],
      renovated: false,
    },
    options: ["엘리베이터", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "중앙로역 1호선", distanceM: 220 },
      { category: "버스", name: "동성로 버스정류장", distanceM: 100 },
    ],
  },
  {
    id: "dalseo-wolbae-apt",
    title: "달서구 월배 푸르지오 아파트",
    dealType: "매매",
    propertyType: "아파트",
    listingType: "일반",
    price: "4억 8,000",
    priceValue: 48000,
    city: "대구",
    district: "달서구",
    areaM2: 84,
    floor: "9/20층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: [],
    gradient: "from-blue-950 via-slate-900 to-slate-800",
    address: "대구광역시 달서구 월배로 210",
    propertyNumber: "D-2026-0301",
    maintenanceFee: "17만원/월",
    direction: "남향",
    builtYear: 2016,
    moveInDate: "협의 가능",
    images: [PHOTOS.aptExt1, PHOTOS.livingRoom],
    description: {
      features: ["월배역 3호선 도보 10분", "대단지 학군 인접"],
      pros: ["월배시장 도보권", "대형마트 인접"],
      cautions: ["출퇴근 시간 진입로 정체"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장"],
    nearby: [
      { category: "지하철", name: "월배역 3호선", distanceM: 800 },
      { category: "학교", name: "월배초등학교", distanceM: 350 },
      { category: "마트", name: "홈플러스 성서점", distanceM: 1200 },
    ],
  },
  {
    id: "dalseo-seongseo-office",
    title: "달서구 성서산업단지 사무실",
    dealType: "매매",
    propertyType: "사무실",
    listingType: "일반",
    price: "9억",
    priceValue: 90000,
    city: "대구",
    district: "달서구",
    areaM2: 165,
    floor: "3/6층",
    bedroomCount: 0,
    bathroomCount: 1,
    badges: [],
    gradient: "from-blue-950 via-slate-900 to-slate-800",
    address: "대구광역시 달서구 성서공단로 77",
    propertyNumber: "D-2026-0410",
    maintenanceFee: "32만원/월",
    direction: "남향",
    builtYear: 2013,
    moveInDate: "협의 가능",
    images: [PHOTOS.officeGlass, PHOTOS.skylineNight2],
    description: {
      features: ["성서산업단지 중심부", "제조업·물류 기업 밀집 지역"],
      pros: ["대형 화물 승강기 보유", "전용 주차 10면"],
      cautions: ["출퇴근 시간 산단 진입로 혼잡"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "성서산업단지역 2호선", distanceM: 500 },
      { category: "마트", name: "이마트 성서점", distanceM: 1100 },
    ],
  },
  {
    id: "dong-sincheon-apt",
    title: "동구 신천 리버파크 아파트",
    dealType: "전세",
    propertyType: "아파트",
    listingType: "일반",
    price: "3억 6,000",
    priceValue: 36000,
    city: "대구",
    district: "동구",
    areaM2: 76,
    floor: "14/22층",
    bedroomCount: 2,
    bathroomCount: 1,
    badges: ["NEW"],
    gradient: "from-indigo-950 via-blue-900 to-sky-900",
    address: "대구광역시 동구 신천동 첨단로 32",
    propertyNumber: "D-2026-0488",
    maintenanceFee: "16만원/월",
    direction: "북서향",
    builtYear: 2023,
    moveInDate: "2026-04 입주 가능",
    images: [PHOTOS.aptExt1, PHOTOS.livingRoom, PHOTOS.skylineNight1],
    description: {
      features: ["신천 조망 세대", "혁신도시 공공기관 인접"],
      pros: ["신축 커뮤니티 라운지", "동대구역 KTX 차량 10분"],
      cautions: ["일부 세대 야간 조명 반사"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장", "CCTV", "보안"],
    nearby: [
      { category: "지하철", name: "동대구역 1호선", distanceM: 1400 },
      { category: "공원", name: "신천둔치공원", distanceM: 250 },
      { category: "병원", name: "칠곡경대병원", distanceM: 2200 },
    ],
  },
  {
    id: "dong-yulha-newtown",
    title: "동구 율하 신도시 분양 아파트",
    dealType: "매매",
    propertyType: "아파트",
    listingType: "분양",
    price: "5억 5,000",
    priceValue: 55000,
    city: "대구",
    district: "동구",
    areaM2: 101,
    floor: "18/29층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["PREMIUM", "NEW"],
    gradient: "from-blue-950 via-sky-900 to-slate-900",
    address: "대구광역시 동구 율하동 율하동로 156",
    propertyNumber: "D-2026-0522",
    maintenanceFee: "19만원/월",
    direction: "남동향",
    builtYear: 2026,
    moveInDate: "2027-02 입주 예정",
    images: [PHOTOS.aptExt1, PHOTOS.skylineNight1, PHOTOS.livingRoom],
    description: {
      features: ["율하공원 인접 신도시 분양 단지", "율하택지지구 중심 상업시설 도보권"],
      pros: ["신설 초등학교 예정", "대형 공원 조망"],
      cautions: ["일부 동호수 계약금 일정 상이"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "붙박이장", "CCTV", "보안"],
    nearby: [
      { category: "공원", name: "율하공원", distanceM: 300 },
      { category: "마트", name: "롯데마트 율하점", distanceM: 700 },
    ],
  },
  {
    id: "buk-chilgok-apt",
    title: "북구 칠곡 3지구 아파트",
    dealType: "전세",
    propertyType: "아파트",
    listingType: "일반",
    price: "2억 8,000",
    priceValue: 28000,
    city: "대구",
    district: "북구",
    areaM2: 84,
    floor: "6/15층",
    bedroomCount: 3,
    bathroomCount: 2,
    badges: ["NEW"],
    gradient: "from-sky-900 via-blue-900 to-slate-900",
    address: "대구광역시 북구 칠곡중앙대로 240",
    propertyNumber: "D-2026-0567",
    maintenanceFee: "15만원/월",
    direction: "남서향",
    builtYear: 2020,
    moveInDate: "즉시입주",
    images: [PHOTOS.aptExt1, PHOTOS.livingRoom],
    description: {
      features: ["칠곡경대병원역 3호선 역세권", "학원가 밀집 지역"],
      pros: ["대형 상업시설 인접", "학원가 도보권"],
      cautions: ["출퇴근 시간 진입로 정체"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "반려동물", "에어컨", "발코니"],
    nearby: [
      { category: "지하철", name: "칠곡경대병원역 3호선", distanceM: 450 },
      { category: "병원", name: "경북대학교병원 칠곡분원", distanceM: 500 },
      { category: "마트", name: "이마트 칠곡점", distanceM: 900 },
    ],
  },
  {
    id: "nam-daemyeong-studio",
    title: "남구 대명동 대학가 원룸형 오피스텔",
    dealType: "월세",
    propertyType: "오피스텔",
    listingType: "일반",
    price: "2,000",
    priceValue: 2000,
    monthlyRent: "월 45",
    monthlyRentValue: 45,
    city: "대구",
    district: "남구",
    areaM2: 33,
    floor: "4/6층",
    bedroomCount: 1,
    bathroomCount: 1,
    badges: ["HOT"],
    gradient: "from-slate-800 via-indigo-900 to-slate-900",
    address: "대구광역시 남구 대명로 88",
    propertyNumber: "D-2026-0603",
    maintenanceFee: "7만원/월",
    direction: "서향",
    builtYear: 2018,
    moveInDate: "즉시입주",
    images: [PHOTOS.livingRoom, PHOTOS.aptExt2],
    description: {
      features: ["영남대·경북대 인접 대학가 상권", "풀옵션 원룸형 구조"],
      pros: ["편의시설 도보권", "관리비 저렴"],
      cautions: ["방학 기간 공실 발생 가능"],
      renovated: false,
    },
    options: ["에어컨", "붙박이장"],
    nearby: [
      { category: "버스", name: "대명동 대학가 정류장", distanceM: 150 },
      { category: "편의점", name: "CU 대명대학점", distanceM: 80 },
    ],
  },
  {
    id: "seo-naedang-house",
    title: "서구 내당동 단독주택",
    dealType: "매매",
    propertyType: "주택",
    listingType: "일반",
    price: "3억 5,000",
    priceValue: 35000,
    city: "대구",
    district: "서구",
    areaM2: 66,
    floor: "지상 2층",
    bedroomCount: 2,
    bathroomCount: 1,
    badges: [],
    gradient: "from-slate-800 via-red-900 to-slate-900",
    address: "대구광역시 서구 내당동 서대구로 145",
    propertyNumber: "D-2026-0644",
    maintenanceFee: "5만원/월",
    direction: "남향",
    builtYear: 2008,
    moveInDate: "협의 가능",
    images: [PHOTOS.house1, PHOTOS.livingRoom],
    description: {
      features: ["구도심 저층 단독주택", "서대구역 KTX 개통 예정 인접"],
      pros: ["개성 있는 리모델링 인테리어", "소규모 마당 보유"],
      cautions: ["주차 공간 협소"],
      renovated: true,
    },
    options: ["반려동물", "에어컨", "발코니"],
    nearby: [
      { category: "지하철", name: "내당역 2호선", distanceM: 500 },
      { category: "편의점", name: "이마트24 내당점", distanceM: 150 },
    ],
  },
  {
    id: "dalseong-technopolis-officetel",
    title: "달성군 테크노폴리스 분양 오피스텔",
    dealType: "매매",
    propertyType: "오피스텔",
    listingType: "분양",
    price: "3억 3,000",
    priceValue: 33000,
    city: "대구",
    district: "달성군",
    areaM2: 72,
    floor: "15/25층",
    bedroomCount: 2,
    bathroomCount: 1,
    badges: ["PREMIUM", "NEW"],
    gradient: "from-blue-950 via-sky-900 to-slate-900",
    address: "대구광역시 달성군 유가읍 테크노폴리스로 300",
    propertyNumber: "D-2026-0689",
    maintenanceFee: "13만원/월",
    direction: "동향",
    builtYear: 2026,
    moveInDate: "2026-11 입주 예정",
    images: [PHOTOS.aptExt2, PHOTOS.officeGlass, PHOTOS.livingRoom],
    description: {
      features: ["테크노폴리스 산업단지 배후 주거", "삼성전자 관련 협력사 밀집 지역"],
      pros: ["신축 분양 프리미엄", "산단 근접 실수요 풍부"],
      cautions: ["차량 없이는 대중교통 다소 불편"],
      renovated: false,
    },
    options: ["주차", "엘리베이터", "에어컨", "CCTV", "보안"],
    nearby: [
      { category: "버스", name: "테크노폴리스 정류장", distanceM: 300 },
      { category: "마트", name: "테크노폴리스 상업지구", distanceM: 600 },
    ],
  },
  {
    id: "dalseong-hyeonpung-house",
    title: "달성군 현풍 전원주택 (경매)",
    dealType: "매매",
    propertyType: "주택",
    listingType: "경매",
    price: "6억",
    priceValue: 60000,
    city: "대구",
    district: "달성군",
    areaM2: 198,
    floor: "지상 2층",
    bedroomCount: 4,
    bathroomCount: 3,
    badges: [],
    gradient: "from-emerald-900 via-slate-900 to-slate-800",
    address: "대구광역시 달성군 현풍읍 현풍로 88",
    propertyNumber: "D-2026-0715",
    maintenanceFee: "9만원/월",
    direction: "남향",
    builtYear: 2015,
    moveInDate: "협의 가능",
    images: [PHOTOS.houseNight, PHOTOS.house1],
    description: {
      features: ["넓은 정원과 개인 마당", "테크노폴리스 산업단지 차량 10분"],
      pros: ["프라이빗한 주거 환경", "반려동물 자유롭게 양육 가능"],
      cautions: ["대중교통 이용 시 마을버스 환승 필요"],
      renovated: true,
    },
    options: ["주차", "반려동물", "에어컨", "발코니", "CCTV"],
    nearby: [
      { category: "학교", name: "현풍초등학교", distanceM: 600 },
      { category: "마트", name: "현풍 하나로마트", distanceM: 1300 },
    ],
  },
];

export const featuredProperties: Property[] = properties.slice(0, 6);

export const popularRegions: Region[] = [
  { id: "suseong", name: "수성구", city: "대구", listingCount: 984, avgPricePerPyeong: "2,480만원", gradient: "from-blue-900 to-slate-900" },
  { id: "jung", name: "중구", city: "대구", listingCount: 512, avgPricePerPyeong: "1,820만원", gradient: "from-slate-900 to-amber-900" },
  { id: "dalseo", name: "달서구", city: "대구", listingCount: 861, avgPricePerPyeong: "1,540만원", gradient: "from-slate-800 to-blue-900" },
  { id: "dong", name: "동구", city: "대구", listingCount: 733, avgPricePerPyeong: "1,460만원", gradient: "from-indigo-900 to-slate-800" },
  { id: "buk", name: "북구", city: "대구", listingCount: 692, avgPricePerPyeong: "1,320만원", gradient: "from-sky-900 to-blue-950" },
  { id: "nam", name: "남구", city: "대구", listingCount: 344, avgPricePerPyeong: "1,210만원", gradient: "from-indigo-950 to-slate-900" },
  { id: "seo", name: "서구", city: "대구", listingCount: 298, avgPricePerPyeong: "1,080만원", gradient: "from-slate-900 to-red-900" },
  { id: "dalseong", name: "달성군", city: "대구", listingCount: 405, avgPricePerPyeong: "890만원", gradient: "from-emerald-900 to-slate-900" },
];

export const reviews: Review[] = [
  {
    id: "r1",
    author: "김O훈",
    role: "매수 고객",
    content: "수성구 학군 매물을 검색 필터로 30분 만에 찾았습니다. 상담도 빨랐어요.",
    rating: 5,
  },
  {
    id: "r2",
    author: "이O영",
    role: "임차인",
    content: "대구 구별 시세 비교가 한눈에 보여서 결정이 쉬웠습니다. 상세 페이지 정보가 정말 꼼꼼해요.",
    rating: 5,
  },
  {
    id: "r3",
    author: "박O민",
    role: "투자자",
    content: "AI 추천 매물이 실제로 관심사와 잘 맞아서 놀랐습니다. 인기 지역 데이터도 유용했어요.",
    rating: 4,
  },
  {
    id: "r4",
    author: "최O진",
    role: "임대인",
    content: "매물 등록부터 문의 관리까지 프로세스가 깔끔합니다. 담당 중개사님과 소통도 원활했어요.",
    rating: 5,
  },
];

export const staffMembers = ["김민준", "이서연", "박도윤", "최지호"];

export const inquiries: Inquiry[] = [
  {
    id: "inq-1001",
    name: "정하윤",
    phone: "010-1234-5678",
    message: "수성구 범어 센트럴 아파트 방문 상담을 신청하고 싶습니다. 이번 주 토요일 오후 가능할까요?",
    propertyTitle: "수성구 범어 센트럴 아파트",
    status: "진행",
    assignee: "김민준",
    memo: "토요일 14시 방문 예약 확정, 주차 안내 필요",
    createdAt: "2026-07-20T09:12:00.000Z",
  },
  {
    id: "inq-1002",
    name: "오세훈",
    phone: "010-2345-6789",
    message: "동구 율하 신도시 분양 아파트 잔여 세대 여부 문의드립니다.",
    propertyTitle: "동구 율하 신도시 분양 아파트",
    status: "접수",
    assignee: "",
    memo: "",
    createdAt: "2026-07-21T02:40:00.000Z",
  },
  {
    id: "inq-1003",
    name: "강수빈",
    phone: "010-3456-7890",
    message: "달서구 성서산업단지 사무실 임대 조건도 가능한지 궁금합니다.",
    propertyTitle: "달서구 성서산업단지 사무실",
    status: "완료",
    assignee: "이서연",
    memo: "임대 불가, 매매만 진행 안내 완료",
    createdAt: "2026-07-18T05:05:00.000Z",
  },
  {
    id: "inq-1004",
    name: "문지훈",
    phone: "010-4567-8901",
    message: "달성군 현풍 전원주택 경매 절차와 명도 관련해서 상담받고 싶어요.",
    propertyTitle: "달성군 현풍 전원주택 (경매)",
    status: "접수",
    assignee: "박도윤",
    memo: "",
    createdAt: "2026-07-22T11:30:00.000Z",
  },
  {
    id: "inq-1005",
    name: "한소율",
    phone: "010-5678-9012",
    message: "타 지역에서 이사 예정인데, 전반적으로 대구 전세 매물 추천받을 수 있을까요?",
    status: "취소",
    assignee: "",
    memo: "고객 요청으로 상담 취소",
    createdAt: "2026-07-15T07:20:00.000Z",
  },
];

export const banners: Banner[] = [
  {
    id: "ban-1",
    title: "프리미엄 신규 입주 매물 특별전",
    subtitle: "동구 율하·달성군 테크노폴리스 신축 분양 매물 모음",
    href: "/search?type=new-sale",
    active: true,
    gradient: "from-blue-900 via-sky-800 to-slate-900",
  },
  {
    id: "ban-2",
    title: "급매 특가 매물전",
    subtitle: "시세보다 낮은 대구 급매 매물을 지금 확인하세요",
    href: "/search?type=urgent",
    active: true,
    gradient: "from-slate-900 via-amber-900 to-slate-800",
  },
  {
    id: "ban-3",
    title: "AI 맞춤 추천 서비스 오픈",
    subtitle: "관심 조건만 입력하면 AI가 매물을 추천해드려요",
    href: "/",
    active: false,
    gradient: "from-indigo-900 via-blue-900 to-slate-900",
  },
];

export const stats: StatItem[] = [
  { id: "listings", label: "등록 매물", value: 18210, suffix: "+" },
  { id: "deals", label: "거래 완료", value: 5480, suffix: "+" },
  { id: "visitors", label: "월간 방문자", value: 263000, suffix: "+" },
  { id: "reviews", label: "고객 리뷰", value: 3340, suffix: "+" },
];

export const visitorTrend: { date: string; visitors: number }[] = [
  { date: "07-10", visitors: 1840 },
  { date: "07-11", visitors: 2020 },
  { date: "07-12", visitors: 1960 },
  { date: "07-13", visitors: 2180 },
  { date: "07-14", visitors: 2310 },
  { date: "07-15", visitors: 2100 },
  { date: "07-16", visitors: 1950 },
  { date: "07-17", visitors: 2230 },
  { date: "07-18", visitors: 2390 },
  { date: "07-19", visitors: 2480 },
  { date: "07-20", visitors: 2240 },
  { date: "07-21", visitors: 2190 },
  { date: "07-22", visitors: 2420 },
  { date: "07-23", visitors: 2542 },
];

export const topSearchedKeywords: { keyword: string; count: number }[] = [
  { keyword: "수성구 범어동 아파트", count: 984 },
  { keyword: "동성로 상가 매매", count: 712 },
  { keyword: "대명동 원룸", count: 645 },
  { keyword: "칠곡 전세 아파트", count: 511 },
  { keyword: "테크노폴리스 오피스텔 분양", count: 338 },
];

export const topViewedProperties: { title: string; views: number }[] = [
  { title: "수성구 범어 센트럴 아파트", views: 3820 },
  { title: "동구 율하 신도시 분양 아파트", views: 2910 },
  { title: "달성군 테크노폴리스 분양 오피스텔", views: 2340 },
  { title: "달서구 월배 푸르지오 아파트", views: 1870 },
  { title: "중구 동성로 코너 상가 (급매)", views: 1510 },
];

export const newsArticles: NewsArticle[] = [
  {
    id: "market-trend-2026-q1",
    title: "2026년 1분기 대구·경북권 아파트 거래량, 전분기 대비 완만한 회복세",
    excerpt: "역세권 신축 단지를 중심으로 거래가 늘며 매매 심리가 점차 살아나는 모습입니다.",
    content: [
      "2026년 1분기 대구·경북권 아파트 거래량이 전분기 대비 완만한 회복세를 보이고 있습니다. 특히 역세권 신축 단지를 중심으로 거래가 늘며 매매 심리가 점차 살아나는 모습입니다.",
      "부동산 업계 관계자들은 금리 안정과 함께 실수요자들의 매수 심리가 회복되고 있다고 분석합니다. 다만 구별 편차는 여전히 크게 나타나고 있어, 수성구와 동대구역 인접 단지에 거래가 집중되는 양상입니다.",
      "전문가들은 2분기에도 이 같은 흐름이 이어질 것으로 전망하면서도, 공급 물량 추이와 정책 변화에 따라 시장 분위기가 달라질 수 있다고 조언했습니다.",
    ],
    category: "시장동향",
    publishedAt: "2026-01-14",
  },
  {
    id: "policy-update-jeonse",
    title: "전세보증금 반환보증 가입 요건 완화, 임차인 부담 줄어드나",
    excerpt: "정부가 발표한 개정안의 주요 내용과 세입자가 챙겨야 할 체크리스트를 정리했습니다.",
    content: [
      "정부가 전세보증금 반환보증 가입 요건을 완화하는 개정안을 발표했습니다. 이번 개정으로 그동안 보증 가입이 어려웠던 일부 주택 유형의 임차인들도 보증금 보호를 받을 수 있게 됐습니다.",
      "주요 개정 내용으로는 보증한도 상향, 심사 서류 간소화, 온라인 신청 절차 확대 등이 포함됩니다. 국토교통부는 이를 통해 임차인의 보증금 미반환 위험이 크게 줄어들 것으로 기대한다고 밝혔습니다.",
      "세입자는 계약 전 반환보증 가입 가능 여부를 미리 확인하고, 등기부등본상 권리관계와 선순위 채권을 꼼꼼히 점검하는 것이 중요합니다.",
    ],
    category: "정책",
    publishedAt: "2026-02-03",
  },
  {
    id: "region-report-suseong",
    title: "수성구, '대구의 강남' 프리미엄에 힘입어 실수요 꾸준",
    excerpt: "범어동 학군 수요와 2호선 접근성이 어우러지며 실거주 매수 문의가 늘고 있습니다.",
    content: [
      "수성구가 범어동 학군 프리미엄과 2호선 접근성에 힘입어 꾸준한 실수요를 이어가고 있습니다. 대형 학원가와 우수 학군이 어우러지면서 실거주 목적의 매수 문의가 늘고 있는 것으로 나타났습니다.",
      "특히 범어동·만촌동 인접 단지는 학군과 상권을 중시하는 30~40대 수요자들에게 꾸준한 인기를 얻고 있으며, 수성못 일대 정비 사업도 장기적인 관심을 끄는 요인으로 꼽힙니다.",
      "지역 공인중개사들은 대구 도시철도 연장 계획과 함께 중장기적으로도 실수요 기반의 안정적인 흐름이 이어질 것으로 내다봤습니다.",
    ],
    category: "지역리포트",
    publishedAt: "2026-02-18",
  },
  {
    id: "interview-agent-tips",
    title: "[인터뷰] 20년차 공인중개사가 말하는 상가 매물 보는 법",
    excerpt: "권리금, 유동인구, 계약 조건까지 — 상가 투자 전 반드시 확인해야 할 포인트.",
    content: [
      "20년차 베테랑 공인중개사와의 인터뷰를 통해 상가 매물을 볼 때 반드시 확인해야 할 포인트를 정리했습니다.",
      "\"권리금은 반드시 시설·영업·바닥 권리금으로 구분해서 협의해야 합니다. 특히 바닥 권리금은 법적 보호를 받기 어려운 경우가 많아 신중한 접근이 필요합니다\"라고 강조했습니다.",
      "유동인구 조사는 시간대별·요일별로 최소 일주일 이상 직접 관찰하는 것을 추천했으며, 장기 임차인이 있는 경우 계약 갱신 조건과 잔여 기간을 명확히 확인해야 한다고 조언했습니다.",
    ],
    category: "인터뷰",
    publishedAt: "2026-03-02",
  },
];

export const searchKeywords = [
  "수성구 범어동 아파트",
  "주차 가능한 상가",
  "신축 오피스텔",
  "테크노폴리스 분양",
  "성서산업단지 사무실",
  "역세권 전세",
  "반려동물 가능 주택",
  "즉시입주 아파트",
];
